name = "avatar-upload"
main = "src/index.ts"
compatibility_date = "2022-07-31"

node_compat = true

# local
# [vars]
# BASE_WEB3_ENDPOINT = "https://dev.hiddenstate.xyz"
# SUPPORTED_NETWORKS = ["harmony", "harmony-s1", "local", "localhost", "mainnet", "goerli", "ropsten"]
# REGISTRY_ADDRESS = "0xa4Fed0fb24Ba68273f0F581227433F47C5D25E25"
# WRAPPER_ADDRESS = '{"local": "0x77db16Bfb930C609ECc5D2618F657329371d2708",  "mainnet": "", "goerli": "0x582224b8d4534F4749EFA4f22eF7241E0C56D4B8", "ropsten": "0xF82155e2a43Be0871821E9654Fc8Ae894FB8307C" }'
# MULTICALL_ADDRESS = "0x60D4140b5772b94b928b0999079c1f60765f1FAc"
# BASE_REGISTRAR_ADDRESS = "0x2E44a57dB0bF4F2FaaC4D6332c17Ef74AC62afD3"

# s1
[vars]
BASE_WEB3_ENDPOINT = "https://s1.api.harmony.one"
SUPPORTED_NETWORKS = ["harmony", "harmony-s1", "local", "localhost", "mainnet", "goerli", "ropsten"]
REGISTRY_ADDRESS = "0xE7f8eFEef65649025E9452E288cA31f47640cDe8"
WRAPPER_ADDRESS = '{"harmony-s1": "0xe054f38e200E2FF6F3c3B603d287911e49297573" }'
MULTICALL_ADDRESS = "0xFc1bbb03556653CCDf15E4068f828DBBac9da78C"
BASE_REGISTRAR_ADDRESS = "0xc578ef0B7377F7674f5E86eE896BCF1C6729BCEA"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = 'ens-harmony-s1'
preview_bucket_name = 'ens-harmony-s1-preview'